refactor: helm chart
MapColonies/tiles-splitter pull request #31
Opened 2024-01-03 13:16 UTC by CL-SHLOMIKONCHA

2024-01-14 15:52 UTC, asafMasa requested changes

2024-01-14 15:52 UTC, asafMasa commented on helm/templates/_resources.tpl
> +{{- end }}
end of file

2024-01-14 15:52 UTC, asafMasa commented on helm/templates/_resources.tpl
> +Create route name as used by the service name label.
remove route

2024-01-14 15:52 UTC, asafMasa commented on helm/templates/_resources.tpl
> +{{- define "ingress.fullname" -}}
remove ingress

2024-01-14 15:53 UTC, CL-SHLOMIKONCHA commented on helm/templates/_resources.tpl
> +{{- end }}
fixed

2024-01-14 15:54 UTC, CL-SHLOMIKONCHA commented on helm/templates/_resources.tpl
> +Create route name as used by the service name label.
fixed

2024-01-14 15:54 UTC, CL-SHLOMIKONCHA commented on helm/templates/_resources.tpl
> +{{- define "ingress.fullname" -}}
fixed

2024-01-15 09:19 UTC, asafMasa approved these changes

2024-01-17 08:14 UTC, merged